// Package rustemit emits serde models and reqwest clients from OpenAPI contracts.
package rustemit

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strconv"
	"strings"
	"unicode"

	"github.com/responsibleapi/oasmith/internal/clientgen"
	"github.com/responsibleapi/oasmith/internal/openapi"
)

// Options configures Rust source emission.
type Options struct{ OutDir string }

type emitter struct {
	schemas     map[string]*openapi.Schema
	definitions map[string]string
}

// Emit writes Rust serde models, optionally including a reqwest client.
func Emit(doc *openapi.Document, opts Options, client bool) error {
	e := &emitter{schemas: doc.Components.Schemas, definitions: map[string]string{}}
	for _, name := range doc.SchemaNames() {
		e.define(typeName(name), doc.Components.Schemas[name])
	}
	var methods strings.Builder
	if client {
		operations, err := clientgen.Analyze(doc)
		if err != nil {
			return fmt.Errorf("analyze Rust client: %w", err)
		}
		methods.WriteString(clientPrelude)
		for _, operation := range operations {
			if operation.RequestBody.Multipart != nil {
				return fmt.Errorf("rust operation %s: sequential multipart is unsupported", operation.Route.Operation.OperationID)
			}
			methods.WriteString(e.operation(operation))
		}
		methods.WriteString("}\n")
	}
	var out strings.Builder
	out.WriteString("// Code generated by oasmith. DO NOT EDIT.\n#![allow(dead_code, clippy::large_enum_variant, clippy::enum_variant_names)]\nuse serde::{Deserialize, Serialize};\n\n")
	names := make([]string, 0, len(e.definitions))
	for name := range e.definitions {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		out.WriteString(e.definitions[name])
		out.WriteString("\n")
	}
	out.WriteString(methods.String())
	if err := os.MkdirAll(opts.OutDir, 0o755); err != nil {
		return fmt.Errorf("create Rust output: %w", err)
	}
	if err := os.WriteFile(filepath.Join(opts.OutDir, "mod.rs"), []byte(out.String()), 0o644); err != nil {
		return fmt.Errorf("write Rust output: %w", err)
	}
	return nil
}

func typeName(value string) string { return openapi.ExportName(value) }

func snake(value string) string {
	var out []rune
	runes := []rune(value)
	for index, r := range runes {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) {
			if len(out) > 0 && out[len(out)-1] != '_' {
				out = append(out, '_')
			}
			continue
		}
		if unicode.IsUpper(r) && index > 0 && len(out) > 0 && out[len(out)-1] != '_' &&
			(unicode.IsLower(runes[index-1]) || unicode.IsDigit(runes[index-1]) || (index+1 < len(runes) && unicode.IsLower(runes[index+1]))) {
			out = append(out, '_')
		}
		out = append(out, unicode.ToLower(r))
	}
	result := strings.Trim(string(out), "_")
	if result == "self" || result == "super" || result == "crate" {
		return result + "_value"
	}
	if result == "" {
		result = "value"
	}
	if unicode.IsDigit([]rune(result)[0]) {
		result = "x_" + result
	}
	if slices.Contains([]string{"type", "ref", "enum", "struct", "fn", "mod", "self", "super", "crate", "match", "loop", "in", "as", "move", "where", "async", "await", "use", "pub", "const", "static", "impl", "trait", "dyn", "let", "for", "while", "return", "true", "false", "box", "gen"}, result) {
		return "r#" + result
	}
	return result
}

func (e *emitter) rustType(schema *openapi.Schema, name string) string {
	if schema == nil {
		return "serde_json::Value"
	}
	if schema.Ref != "" {
		return typeName(schema.Ref[strings.LastIndex(schema.Ref, "/")+1:])
	}
	if schema.Type.Has("null") && len(schema.Type) > 1 {
		copySchema := *schema
		copySchema.Type = nil
		for _, typ := range schema.Type {
			if typ != "null" {
				copySchema.Type = append(copySchema.Type, typ)
			}
		}
		return "std::option::Option<" + e.rustType(&copySchema, name) + ">"
	}
	if len(schema.Properties) > 0 || len(schema.OneOf) > 0 || len(schema.Enum) > 0 || schema.Const != nil {
		e.define(name, schema)
		return name
	}
	switch schema.Type.First() {
	case "string":
		return "std::string::String"
	case "integer":
		return "i64"
	case "number":
		return "f64"
	case "boolean":
		return "bool"
	case "array":
		return "std::vec::Vec<" + e.rustType(schema.Items, name+"Item") + ">"
	case "null":
		return "()"
	default:
		return "serde_json::Value"
	}
}

func (e *emitter) define(name string, schema *openapi.Schema) {
	if _, exists := e.definitions[name]; exists {
		return
	}
	e.definitions[name] = ""
	var out strings.Builder
	switch {
	case schema != nil && (len(schema.Enum) > 0 || schema.Const != nil):
		values := schema.Enum
		if value, ok := schema.Const.(string); ok {
			values = []string{value}
		}
		if len(values) == 0 {
			e.definitions[name] = "pub type " + name + " = serde_json::Value;\n"
			return
		}
		out.WriteString("#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]\npub enum " + name + " {\n")
		used := map[string]bool{}
		for index, value := range values {
			variant := typeName(value)
			if value == strings.ToUpper(value) {
				variant = typeName(strings.ToLower(value))
			}
			if variant == "" || used[variant] {
				variant = fmt.Sprintf("Value%d", index)
			}
			used[variant] = true
			fmt.Fprintf(&out, "    #[serde(rename = %s)]\n    %s,\n", strconv.Quote(value), variant)
		}
		out.WriteString("}\n")
	case schema != nil && len(schema.OneOf) > 0:
		out.WriteString("#[derive(Clone, Debug, Serialize, Deserialize)]\n#[serde(untagged)]\npub enum " + name + " {\n")
		for index, item := range schema.OneOf {
			typ := e.rustType(item, fmt.Sprintf("%sVariant%d", name, index))
			fmt.Fprintf(&out, "    Variant%d(%s),\n", index, typ)
		}
		out.WriteString("}\n")
	case schema != nil && len(schema.Properties) > 0:
		e.object(&out, name, schema)
	default:
		fmt.Fprintf(&out, "pub type %s = %s;\n", name, e.rustType(schema, name+"Value"))
	}
	e.definitions[name] = out.String()
}

func (e *emitter) object(out *strings.Builder, name string, schema *openapi.Schema) {
	out.WriteString("#[derive(Clone, Debug, Serialize, Deserialize)]\n")
	if allowed, ok := schema.AdditionalProperties.(bool); ok && !allowed {
		out.WriteString("#[serde(deny_unknown_fields)]\n")
	}
	out.WriteString("pub struct " + name + " {\n")
	keys := make([]string, 0, len(schema.Properties))
	for key := range schema.Properties {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	for _, key := range keys {
		typ := e.rustType(schema.Properties[key], name+typeName(key))
		fmt.Fprintf(out, "    #[serde(rename = %s", strconv.Quote(key))
		if !slices.Contains(schema.Required, key) {
			out.WriteString(", default, skip_serializing_if = \"Option::is_none\"")
			typ = "std::option::Option<" + typ + ">"
		}
		fmt.Fprintf(out, ")]\n    pub %s: %s,\n", snake(key), typ)
	}
	out.WriteString("}\n")
}

func (e *emitter) operation(op clientgen.Operation) string {
	name := typeName(op.Route.Operation.OperationID)
	var params, body strings.Builder
	params.WriteString("#[derive(Clone, Debug)]\npub struct " + name + "Params {\n")
	fmt.Fprintf(&body, "    pub fn %s(&self", snake(op.Route.Operation.OperationID))
	hasParams := len(op.Route.Operation.Parameters) > 0 || op.RequestBody.JSON != nil || op.RequestBody.Raw != nil
	if hasParams {
		fmt.Fprintf(&body, ", params: %sParams", name)
	}
	body.WriteString(") -> reqwest::RequestBuilder {\n")
	fmt.Fprintf(&body, "        let path = %s.to_owned();\n", strconv.Quote(op.Route.Path))
	for _, param := range op.Route.Operation.Parameters {
		typ := e.rustType(param.Schema, name+typeName(param.Name))
		if !param.Required {
			typ = "std::option::Option<" + typ + ">"
		}
		fmt.Fprintf(&params, "    pub %s: %s,\n", snake(param.Name), typ)
		if param.In == "path" {
			fmt.Fprintf(&body, "        let path = path.replace(%s, &encode_path(&params.%s.to_string()));\n", strconv.Quote("{"+param.Name+"}"), snake(param.Name))
		}
	}
	fmt.Fprintf(&body, "        let request = self.http.request(reqwest::Method::%s, format!(\"{}{}\", self.base_url, path)).header(\"Accept\", %s);\n", op.Route.Method, strconv.Quote(op.Accept))
	body.WriteString("        let request = match &self.bearer_token { Some(token) => request.bearer_auth(token), None => request };\n")
	e.parameters(&body, op)
	if op.RequestBody.JSON != nil {
		typ := e.rustType(op.RequestBody.JSON.Schema, name+"Body")
		if op.RequestBody.JSON.Required {
			fmt.Fprintf(&params, "    pub body: %s,\n", typ)
			body.WriteString("        let request = request.json(&params.body);\n")
		} else {
			fmt.Fprintf(&params, "    pub body: Option<%s>,\n", typ)
			body.WriteString("        let request = match params.body { Some(body) => request.json(&body), None => request };\n")
		}
	}
	if op.RequestBody.Raw != nil {
		if op.RequestBody.Raw.Required {
			params.WriteString("    pub body: std::vec::Vec<u8>,\n")
			fmt.Fprintf(&body, "        let request = request.header(\"Content-Type\", %s).body(params.body);\n", strconv.Quote(op.RequestBody.Raw.MediaType))
		} else {
			params.WriteString("    pub body: std::option::Option<std::vec::Vec<u8>>,\n")
			fmt.Fprintf(&body, "        let request = match params.body { Some(body) => request.header(\"Content-Type\", %s).body(body), None => request };\n", strconv.Quote(op.RequestBody.Raw.MediaType))
		}
	}

	params.WriteString("}\n")
	if hasParams {
		e.definitions[name+"Params"] = params.String()
	}
	e.response(op, name)
	source := body.String()
	last := strings.LastIndex(source, "        let request = ")
	return source[:last] + "        " + strings.TrimSuffix(source[last+len("        let request = "):], ";\n") + "\n    }\n"
}

func (e *emitter) parameters(body *strings.Builder, op clientgen.Operation) {
	for _, param := range op.Route.Operation.Parameters {
		field := snake(param.Name)
		switch param.In {
		case "query":
			switch {
			case param.Schema.Type.Has("array"):
				query := fmt.Sprintf("request.query(&value.iter().map(|item| (%s, item)).collect::<std::vec::Vec<_>>())", strconv.Quote(param.Name))
				if param.Required {
					fmt.Fprintf(body, "        let value = &params.%s;\n        let request = %s;\n", field, query)
				} else {
					fmt.Fprintf(body, "        let request = match &params.%s { Some(value) => %s, None => request };\n", field, query)
				}
			case param.Required:
				fmt.Fprintf(body, "        let request = request.query(&[(%s, &params.%s)]);\n", strconv.Quote(param.Name), field)
			default:
				fmt.Fprintf(body, "        let request = match params.%s { Some(value) => request.query(&[(%s, value)]), None => request };\n", field, strconv.Quote(param.Name))
			}
		case "header":
			if param.Required {
				fmt.Fprintf(body, "        let request = request.header(%s, params.%s.to_string());\n", strconv.Quote(param.Name), field)
			} else {
				fmt.Fprintf(body, "        let request = match params.%s { Some(value) => request.header(%s, value.to_string()), None => request };\n", field, strconv.Quote(param.Name))
			}
		}
	}
}

func (e *emitter) response(op clientgen.Operation, name string) {
	var response strings.Builder
	fmt.Fprintf(&response, "#[derive(Debug)]\npub enum %sResponse {\n", name)
	for _, res := range op.Responses {
		typ := e.rustType(res.Schema, fmt.Sprintf("%sStatus%d", name, res.Status))
		switch {
		case res.SSE:
			typ = "reqwest::Response"
		case !res.HasBody():
			typ = "()"
		case !res.JSON():
			typ = "Vec<u8>"
		}
		fmt.Fprintf(&response, "    Status%d(%s),\n", res.Status, typ)
	}
	response.WriteString("    Unexpected(reqwest::Response),\n}\n")
	fmt.Fprintf(&response, "impl %sResponse {\n    pub async fn decode(response: reqwest::Response) -> Result<Self, reqwest::Error> {\n        Ok(match response.status().as_u16() {\n", name)
	for _, res := range op.Responses {
		value := "response.json().await?"
		switch {
		case res.SSE:
			value = "response"
		case !res.HasBody():
			value = "()"
		case !res.JSON():
			value = "response.bytes().await?.to_vec()"
		}
		fmt.Fprintf(&response, "            %d => Self::Status%d(%s),\n", res.Status, res.Status, value)
	}
	response.WriteString("            _ => Self::Unexpected(response),\n        })\n    }\n}\n")
	e.definitions[name+"Response"] = response.String()
}

const clientPrelude = `
#[derive(Clone, Debug)]
pub struct Client {
    http: reqwest::Client,
    base_url: String,
    bearer_token: Option<String>,
}
fn encode_path(value: &str) -> String {
    value.bytes().map(|byte| {
        if byte.is_ascii_alphanumeric() || b"-._~".contains(&byte) {
            char::from(byte).to_string()
        } else { format!("%{byte:02X}") }
    }).collect()
}
impl Client {
    pub fn new(http: reqwest::Client, base_url: String, bearer_token: Option<String>) -> Self {
        Self { http, base_url: base_url.trim_end_matches('/').to_owned(), bearer_token }
    }
`
