// Generated by OASmith. Do not edit.
import 'dart:convert';

import 'package:http/http.dart' as http;

import 'models.dart';
export 'models.dart';

class ApiStatusException implements Exception {
  const ApiStatusException(this.statusCode);
  final int statusCode;
  @override
  String toString() => 'API returned HTTP $statusCode';
}

class PublicApiClient {
  PublicApiClient({
    required this.baseUri,
    required this.send,
    this.responseError,
    this.readBody,
  });
  final Uri baseUri;
  final Future<http.StreamedResponse> Function(http.BaseRequest) send;
  final Future<Exception> Function(http.StreamedResponse)? responseError;
  final Future<List<int>> Function(http.StreamedResponse, int)? readBody;

  Uri _uri(String path, Map<String, dynamic> query) {
    if (!path.startsWith('/') || path.startsWith('//'))
      throw const FormatException('API path must be absolute');
    final uri = baseUri
        .resolve(path)
        .replace(queryParameters: query.isEmpty ? null : query);
    if (uri.origin != baseUri.origin)
      throw const FormatException('API path escapes configured origin');
    return uri;
  }

  String _wire(Object? value) {
    final encoded = encodePublicJson(value);
    if (encoded is String) return encoded;
    if (encoded is num || encoded is bool) return encoded.toString();
    throw const FormatException('API parameter must be scalar');
  }

  Future<Exception> _error(http.StreamedResponse response) async =>
      responseError == null
      ? ApiStatusException(response.statusCode)
      : responseError!(response);
  Future<List<int>> _readBounded(http.StreamedResponse response) async {
    if (readBody != null) return readBody!(response, 4 << 20);
    final bytes = <int>[];
    await for (final chunk in response.stream) {
      if (bytes.length + chunk.length > (4 << 20))
        throw const FormatException('API response exceeds 4 MiB');
      bytes.addAll(chunk);
    }
    return bytes;
  }

  Future<http.StreamedResponse> watchEvents() async {
    final query = <String, dynamic>{};
    final request = http.Request("GET", _uri('/events', query));
    request.headers['Accept'] = "text/event-stream";
    final response = await send(request);
    if (!const <int>{200}.contains(response.statusCode))
      throw await _error(response);
    return response;
  }

  Future<void> patchThing({CreateThing? body}) async {
    final query = <String, dynamic>{};
    final request = http.Request("POST", _uri('/optional-json', query));
    request.headers['Accept'] = "*/*";
    if (body != null) {
      request.headers['Content-Type'] = 'application/json';
      request.body = jsonEncode(encodePublicJson(body));
    }
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<void> uploadOptionalMedia({List<int>? body}) async {
    final query = <String, dynamic>{};
    final request = http.Request("POST", _uri('/optional-raw', query));
    request.headers['Accept'] = "*/*";
    if (body != null) {
      request.headers['Content-Type'] = "application/octet-stream";
      request.bodyBytes = body;
    }
    final response = await send(request);
    if (!const <int>{204}.contains(response.statusCode))
      throw await _error(response);
    await _readBounded(response);
    return;
  }

  Future<Thing> createThing({
    required String thingId,
    String? tag,
    required bool notify,
    List<String>? label,
    required String xRequestId,
    required CreateThing body,
  }) async {
    final query = <String, dynamic>{};
    if (tag != null) query["tag"] = _wire(tag);
    query["notify"] = _wire(notify);
    if (label != null) query["label"] = label.map(_wire).toList();
    final request = http.Request(
      "POST",
      _uri('/things/${Uri.encodeComponent(_wire(thingId))}', query),
    );
    request.headers['Accept'] = "application/json";
    request.headers["x-request-id"] = _wire(xRequestId);
    request.headers['Content-Type'] = 'application/json';
    request.body = jsonEncode(encodePublicJson(body));
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return Thing.fromJson(jsonDecode(utf8.decode(bytes)));
  }

  Future<Thing> uploadMedia({
    required String owner,
    required String uploadType,
    required List<int> body,
  }) async {
    final query = <String, dynamic>{};
    query["uploadType"] = _wire(uploadType);
    final request = http.Request(
      "POST",
      _uri('/uploads/${Uri.encodeComponent(_wire(owner))}', query),
    );
    request.headers['Accept'] = "application/json";
    request.headers['Content-Type'] = "application/octet-stream";
    request.bodyBytes = body;
    final response = await send(request);
    if (!const <int>{201}.contains(response.statusCode))
      throw await _error(response);
    final bytes = await _readBounded(response);
    return Thing.fromJson(jsonDecode(utf8.decode(bytes)));
  }
}
