// Generated by OASmith. Do not edit.

abstract interface class PublicJsonValue {
  Object? toJson();
}

Map<String, Object?> expectPublicMap(Object? value) {
  if (value is! Map) throw const FormatException('expected JSON object');
  final result = <String, Object?>{};
  for (final entry in value.entries) {
    if (entry.key is! String)
      throw const FormatException('expected JSON string key');
    result[entry.key as String] = entry.value;
  }
  return result;
}

List<Object?> expectPublicList(Object? value) {
  if (value is! List) throw const FormatException('expected JSON array');
  return value;
}

String expectPublicString(Object? value) {
  if (value is! String) throw const FormatException('expected JSON string');
  return value;
}

int expectPublicInt(Object? value) {
  if (value is! int) throw const FormatException('expected JSON integer');
  return value;
}

double expectPublicDouble(Object? value) {
  if (value is! num) throw const FormatException('expected JSON number');
  return value.toDouble();
}

bool expectPublicBool(Object? value) {
  if (value is! bool) throw const FormatException('expected JSON boolean');
  return value;
}

Object? requirePublicField(Map<String, Object?> value, String key) {
  if (!value.containsKey(key))
    throw FormatException('missing required field: $key');
  return value[key];
}

Object? encodePublicJson(Object? value) {
  if (value is PublicJsonValue) return value.toJson();
  if (value is List) return value.map(encodePublicJson).toList();
  if (value is Map)
    return value.map(
      (key, item) => MapEntry(key.toString(), encodePublicJson(item)),
    );
  return value;
}

sealed class Event implements PublicJsonValue {
  const Event();
  factory Event.fromJson(Object? value) {
    final map = expectPublicMap(value);
    switch (map["event"]) {
      case "progress":
        return EventVariant1.fromJson(value);
      case "terminal":
        return EventVariant2.fromJson(value);
      default:
        throw FormatException('unknown Event discriminator: ${map["event"]}');
    }
  }
}

sealed class TerminalResult implements PublicJsonValue {
  const TerminalResult();
  factory TerminalResult.fromJson(Object? value) {
    final map = expectPublicMap(value);
    switch (map["status"]) {
      case "completed":
        return CompletedResult.fromJson(value);
      case "failed":
        return FailedResult.fromJson(value);
      default:
        throw FormatException(
          'unknown TerminalResult discriminator: ${map["status"]}',
        );
    }
  }
}

class CompletedResult implements PublicJsonValue, TerminalResult {
  final String status;
  final Thing thing;
  const CompletedResult({required this.status, required this.thing});
  factory CompletedResult.fromJson(Object? raw) {
    final map = expectPublicMap(raw);
    if (requirePublicField(map, "status") != "completed")
      throw const FormatException('invalid status discriminator');
    final status = expectPublicString(requirePublicField(map, "status"));
    final thing = Thing.fromJson(requirePublicField(map, "thing"));
    return CompletedResult(status: status, thing: thing);
  }
  @override
  Map<String, Object?> toJson() => {
    "status": encodePublicJson(status),
    "thing": encodePublicJson(thing),
  };
}

class CreateThing implements PublicJsonValue {
  final String name;
  const CreateThing({required this.name});
  factory CreateThing.fromJson(Object? raw) {
    final map = expectPublicMap(raw);
    final name = expectPublicString(requirePublicField(map, "name"));
    return CreateThing(name: name);
  }
  @override
  Map<String, Object?> toJson() => {"name": encodePublicJson(name)};
}

class EventVariant1 implements Event, PublicJsonValue {
  final String data;
  final String event;
  const EventVariant1({required this.data, required this.event});
  factory EventVariant1.fromJson(Object? raw) {
    final map = expectPublicMap(raw);
    final data = expectPublicString(requirePublicField(map, "data"));
    if (requirePublicField(map, "event") != "progress")
      throw const FormatException('invalid event discriminator');
    final event = expectPublicString(requirePublicField(map, "event"));
    return EventVariant1(data: data, event: event);
  }
  @override
  Map<String, Object?> toJson() => {
    "data": encodePublicJson(data),
    "event": encodePublicJson(event),
  };
}

class EventVariant2 implements Event, PublicJsonValue {
  final String data;
  final String event;
  const EventVariant2({required this.data, required this.event});
  factory EventVariant2.fromJson(Object? raw) {
    final map = expectPublicMap(raw);
    final data = expectPublicString(requirePublicField(map, "data"));
    if (requirePublicField(map, "event") != "terminal")
      throw const FormatException('invalid event discriminator');
    final event = expectPublicString(requirePublicField(map, "event"));
    return EventVariant2(data: data, event: event);
  }
  @override
  Map<String, Object?> toJson() => {
    "data": encodePublicJson(data),
    "event": encodePublicJson(event),
  };
}

class FailedResult implements PublicJsonValue, TerminalResult {
  final String message;
  final String status;
  const FailedResult({required this.message, required this.status});
  factory FailedResult.fromJson(Object? raw) {
    final map = expectPublicMap(raw);
    final message = expectPublicString(requirePublicField(map, "message"));
    if (requirePublicField(map, "status") != "failed")
      throw const FormatException('invalid status discriminator');
    final status = expectPublicString(requirePublicField(map, "status"));
    return FailedResult(message: message, status: status);
  }
  @override
  Map<String, Object?> toJson() => {
    "message": encodePublicJson(message),
    "status": encodePublicJson(status),
  };
}

class Problem implements PublicJsonValue {
  final String message;
  const Problem({required this.message});
  factory Problem.fromJson(Object? raw) {
    final map = expectPublicMap(raw);
    final message = expectPublicString(requirePublicField(map, "message"));
    return Problem(message: message);
  }
  @override
  Map<String, Object?> toJson() => {"message": encodePublicJson(message)};
}

class ProgressEvent implements PublicJsonValue {
  final String kind;
  final int percent;
  const ProgressEvent({required this.kind, required this.percent});
  factory ProgressEvent.fromJson(Object? raw) {
    final map = expectPublicMap(raw);
    if (requirePublicField(map, "kind") != "progress")
      throw const FormatException('invalid kind discriminator');
    final kind = expectPublicString(requirePublicField(map, "kind"));
    final percent = expectPublicInt(requirePublicField(map, "percent"));
    return ProgressEvent(kind: kind, percent: percent);
  }
  @override
  Map<String, Object?> toJson() => {
    "kind": encodePublicJson(kind),
    "percent": encodePublicJson(percent),
  };
}

class TerminalEvent implements PublicJsonValue {
  final String kind;
  final TerminalResult result;
  const TerminalEvent({required this.kind, required this.result});
  factory TerminalEvent.fromJson(Object? raw) {
    final map = expectPublicMap(raw);
    if (requirePublicField(map, "kind") != "terminal")
      throw const FormatException('invalid kind discriminator');
    final kind = expectPublicString(requirePublicField(map, "kind"));
    final result = TerminalResult.fromJson(requirePublicField(map, "result"));
    return TerminalEvent(kind: kind, result: result);
  }
  @override
  Map<String, Object?> toJson() => {
    "kind": encodePublicJson(kind),
    "result": encodePublicJson(result),
  };
}

class Thing implements PublicJsonValue {
  final String id;
  final String name;
  const Thing({required this.id, required this.name});
  factory Thing.fromJson(Object? raw) {
    final map = expectPublicMap(raw);
    final id = expectPublicString(requirePublicField(map, "id"));
    final name = expectPublicString(requirePublicField(map, "name"));
    return Thing(id: id, name: name);
  }
  @override
  Map<String, Object?> toJson() => {
    "id": encodePublicJson(id),
    "name": encodePublicJson(name),
  };
}
