package dartemit

import (
	"fmt"
	"sort"
	"strings"

	"github.com/responsibleapi/oasmith/internal/openapi"
)

func (e *emitter) modelsSource() string {
	var out strings.Builder
	out.WriteString("// Generated by OASmith. Do not edit.\n\n")
	out.WriteString("abstract interface class PublicJsonValue { Object? toJson(); }\n\n")
	out.WriteString(`Map<String, Object?> expectPublicMap(Object? value) {
  if (value is! Map) throw const FormatException('expected JSON object');
  final result = <String, Object?>{};
  for (final entry in value.entries) {
    if (entry.key is! String) throw const FormatException('expected JSON string key');
    result[entry.key as String] = entry.value;
  }
  return result;
}
List<Object?> expectPublicList(Object? value) {
  if (value is! List) throw const FormatException('expected JSON array');
  return value;
}
String expectPublicString(Object? value) {
  if (value is! String) throw const FormatException('expected JSON string');
  return value;
}
int expectPublicInt(Object? value) {
  if (value is! int) throw const FormatException('expected JSON integer');
  return value;
}
double expectPublicDouble(Object? value) {
  if (value is! num) throw const FormatException('expected JSON number');
  return value.toDouble();
}
bool expectPublicBool(Object? value) {
  if (value is! bool) throw const FormatException('expected JSON boolean');
  return value;
}
Object? requirePublicField(Map<String, Object?> value, String key) {
  if (!value.containsKey(key)) throw FormatException('missing required field: $key');
  return value[key];
}
Object? encodePublicJson(Object? value) {
  if (value is PublicJsonValue) return value.toJson();
  if (value is List) return value.map(encodePublicJson).toList();
  if (value is Map) return value.map((key, item) => MapEntry(key.toString(), encodePublicJson(item)));
  return value;
}

`)
	names := e.sortedNames()
	// Unions are declared before variants, so sealed interfaces are available.
	for _, name := range names {
		if e.definitions[name].IsOneOf() {
			e.writeUnion(&out, name, e.definitions[name])
		}
	}
	for _, name := range names {
		schema := e.definitions[name]
		if schema.IsOneOf() {
			continue
		}
		switch {
		case len(schema.Enum) > 0:
			e.writeEnum(&out, name, schema)
		case schema.IsObject() && len(schema.Properties) > 0:
			e.writeObject(&out, name, schema)
		default:
			e.writeAlias(&out, name, schema)
		}
	}
	return out.String()
}

func (e *emitter) writeAlias(out *strings.Builder, name string, schema *openapi.Schema) {
	typ := e.dartType(schema, name)
	if typ == name {
		e.err = fmt.Errorf("dart unsupported alias %s", name)
		return
	}
	fmt.Fprintf(out, "typedef %s = %s;\n", name, typ)
	fmt.Fprintf(out, "%s decode%s(Object? value) => %s;\n\n", name, name, e.decodeExpr(schema, "value", name))
}

func (e *emitter) writeEnum(out *strings.Builder, name string, schema *openapi.Schema) {
	fmt.Fprintf(out, "enum %s implements PublicJsonValue {\n", name)
	used := map[string]bool{}
	for _, value := range schema.Enum {
		member := fieldName(value)
		if used[member] {
			e.err = fmt.Errorf("dart enum %s has duplicate case %q", name, member)
			return
		}
		used[member] = true
		fmt.Fprintf(out, "  %s(%s),\n", member, quote(value))
	}
	fmt.Fprintf(out, "  ;\n  const %s(this.value);\n  final String value;\n", name)
	fmt.Fprintf(out, "  static %s fromJson(Object? value) {\n    for (final item in values) { if (item.value == value) return item; }\n    throw FormatException('unknown %s: $value');\n  }\n", name, name)
	out.WriteString("  @override String toJson() => value;\n}\n\n")
}

func (e *emitter) writeObject(out *strings.Builder, name string, schema *openapi.Schema) {
	interfaces := []string{"PublicJsonValue"}
	interfaces = append(interfaces, e.implemented[name]...)
	sort.Strings(interfaces)
	fmt.Fprintf(out, "class %s implements %s {\n", name, strings.Join(interfaces, ", "))
	required := schema.RequiredSet()
	keys := schema.SortedPropertyNames()
	for _, key := range keys {
		typ := e.dartType(schema.Properties[key], name+typeName(key))
		if !required[key] && !strings.HasSuffix(typ, "?") {
			typ += "?"
		}
		fmt.Fprintf(out, "  final %s %s;\n", typ, fieldName(key))
	}
	fmt.Fprintf(out, "  const %s({", name)
	for _, key := range keys {
		if required[key] {
			out.WriteString("required ")
		}
		fmt.Fprintf(out, "this.%s,", fieldName(key))
	}
	out.WriteString("});\n")
	fmt.Fprintf(out, "  factory %s.fromJson(Object? raw) {\n    final map = expectPublicMap(raw);\n", name)
	if strict, ok := schema.AdditionalProperties.(bool); ok && !strict {
		out.WriteString("    for (final key in map.keys) {\n      if (!const <String>{")
		for _, key := range keys {
			fmt.Fprintf(out, "%s,", quote(key))
		}
		out.WriteString("}.contains(key)) throw FormatException('unexpected JSON field: $key');\n    }\n")
	}
	for _, key := range keys {
		prop := schema.Properties[key]
		source := fmt.Sprintf("map[%s]", quote(key))
		if required[key] {
			source = fmt.Sprintf("requirePublicField(map,%s)", quote(key))
		}
		expr := e.decodeExpr(prop, source, name+typeName(key))
		if !required[key] && !strings.HasSuffix(e.dartType(prop, name+typeName(key)), "?") {
			expr = "(" + source + " == null ? null : " + expr + ")"
		}
		if prop.Const != nil {
			if value, ok := prop.Const.(string); ok {
				fmt.Fprintf(out, "    if (%s != %s) throw const FormatException('invalid %s discriminator');\n", source, quote(value), key)
			}
		}
		fmt.Fprintf(out, "    final %s = %s;\n", fieldName(key), expr)
	}
	fmt.Fprintf(out, "    return %s(", name)
	for _, key := range keys {
		fmt.Fprintf(out, "%s: %s,", fieldName(key), fieldName(key))
	}
	out.WriteString(");\n  }\n")
	out.WriteString("  @override Map<String, Object?> toJson() => {")
	for _, key := range keys {
		field := fieldName(key)
		if required[key] {
			fmt.Fprintf(out, "%s: encodePublicJson(%s),", quote(key), field)
		} else {
			fmt.Fprintf(out, "if (%s != null) %s: encodePublicJson(%s),", field, quote(key), field)
		}
	}
	out.WriteString("};\n}\n\n")
}

func (e *emitter) writeUnion(out *strings.Builder, name string, schema *openapi.Schema) {
	interfaces := append([]string{"PublicJsonValue"}, e.implemented[name]...)
	sort.Strings(interfaces)
	fmt.Fprintf(out, "sealed class %s implements %s {\n  const %s();\n  factory %s.fromJson(Object? value) {\n    final map = expectPublicMap(value);\n", name, strings.Join(interfaces, ", "), name, name)
	tag := e.unionTag(schema)
	if tag != "" {
		fmt.Fprintf(out, "    switch (map[%s]) {\n", quote(tag))
		for index, item := range schema.OneOf {
			resolved := e.resolve(item)
			variant := e.dartType(item, name+fmt.Sprintf("Variant%d", index+1))
			values := e.unionValues(schema, item, resolved, tag)
			sort.Strings(values)
			for _, value := range values {
				fmt.Fprintf(out, "      case %s:\n", quote(value))
			}
			if len(values) > 0 {
				fmt.Fprintf(out, "        return %s;\n", e.decodeExpr(item, "value", variant))
			}
		}
		fmt.Fprintf(out, "      default: throw FormatException('unknown %s discriminator: ${map[%s]}');\n    }\n", name, quote(tag))
	} else {
		for _, item := range schema.OneOf {
			fmt.Fprintf(out, "    try { return %s; } on FormatException { /* next variant */ }\n", e.decodeExpr(item, "value", name))
		}
		fmt.Fprintf(out, "    throw const FormatException('no %s variant matched');\n", name)
	}
	out.WriteString("  }\n}\n\n")
}

func (e *emitter) unionTag(schema *openapi.Schema) string {
	if schema.Discriminator != nil {
		return schema.Discriminator.PropertyName
	}
	for _, item := range schema.OneOf {
		resolved := e.resolve(item)
		if resolved == nil {
			return ""
		}
		for key, property := range resolved.Properties {
			if property.Const == nil {
				continue
			}
			all := true
			for _, other := range schema.OneOf {
				candidate := e.resolve(other)
				if candidate == nil || candidate.Properties[key] == nil || candidate.Properties[key].Const == nil {
					all = false
					break
				}
			}
			if all {
				return key
			}
		}
	}
	return ""
}

func (e *emitter) unionValues(union, item, resolved *openapi.Schema, tag string) []string {
	var values []string
	if union.Discriminator != nil {
		for value, ref := range union.Discriminator.Mapping {
			if item.Ref != "" && openapi.RefName(ref) == openapi.RefName(item.Ref) {
				values = append(values, value)
			}
		}
	}
	if len(values) > 0 {
		return values
	}
	if resolved != nil && resolved.Properties[tag] != nil {
		if value, ok := resolved.Properties[tag].Const.(string); ok {
			return []string{value}
		}
		if len(resolved.Properties[tag].Enum) > 0 {
			return resolved.Properties[tag].Enum
		}
	}
	if item.Ref != "" {
		return []string{openapi.RefName(item.Ref)}
	}
	e.err = fmt.Errorf("dart union variant has no %s discriminator", tag)
	return nil
}

func (e *emitter) decodeExpr(schema *openapi.Schema, value, hint string) string {
	if schema == nil {
		e.err = fmt.Errorf("dart missing decode schema for %s", hint)
		return value
	}
	if schema.Ref != "" {
		name := openapi.RefName(schema.Ref)
		if name == "string" || name == "String" {
			return "expectPublicString(" + value + ")"
		}
		resolved := e.resolve(schema)
		if resolved == nil {
			return value
		}
		if resolved.IsOneOf() || len(resolved.Enum) > 0 || (resolved.IsObject() && len(resolved.Properties) > 0) {
			return typeName(name) + ".fromJson(" + value + ")"
		}
		return "decode" + typeName(name) + "(" + value + ")"
	}
	nullable := schema.Type.Has("null")
	var expr string
	switch {
	case len(schema.OneOf) > 0 || len(schema.Enum) > 0 || (schema.IsObject() && len(schema.Properties) > 0):
		expr = e.register(hint, schema) + ".fromJson(" + value + ")"
	case schema.Type.Has("array"):
		expr = "expectPublicList(" + value + ").map((item) => " + e.decodeExpr(schema.Items, "item", hint+"Item") + ").toList()"
	case schema.Type.Has("string"):
		expr = "expectPublicString(" + value + ")"
	case schema.Type.Has("integer"):
		expr = "expectPublicInt(" + value + ")"
	case schema.Type.Has("number"):
		expr = "expectPublicDouble(" + value + ")"
	case schema.Type.Has("boolean"):
		expr = "expectPublicBool(" + value + ")"
	case schema.Type.Has("object"):
		expr = "expectPublicMap(" + value + ")"
	case schema.Type.Has("null"):
		return "null"
	default:
		e.err = fmt.Errorf("dart unsupported decode for %s", hint)
		return value
	}
	if nullable {
		return "(" + value + " == null ? null : " + expr + ")"
	}
	return expr
}
