env:
  GOLANGCI_LINT_CACHE: ${HOME}/.cache/golangci-lint
taskOptions:
  cache: false
  unixShell: bash
  outputStyle: stream
implicitInputs:
  - /.moon/**/*.yml
  - moon.yml
  - /.github/workflows/ci.yaml
